logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %clr(%5p) %clr(-){faint} %clr(%-80.80logger{79}){cyan} %clr(:) %m%n"

spring:
  application:
    name: eurekaServer  # 服务名

server:
  port: 3000
eureka:
  server:
    enable-self-preservation: false  #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 #设置清理间隔(清理死掉的服务)（单位：毫秒 默认是60*1000）
  instance:
    hostname: eureka  # 实例端口号，host文件中已添加的（127.0.0.1）
  client:
    registerWithEureka: true #不把自己作为一个客户端注册到自己身上
    fetchRegistry: true  #不需要从服务端获取注册信息（因为在这里自己就是服务端，而且已经禁用自己注册了）
    serviceUrl: #微服务要注册到的地址.
      #http://localhost:3000/eureka
      defaultZone: http://eureka1:3001/eureka, http://eureka2:3002/eureka

